import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MARKER = '<!-- KITCHEN-AI-GENERATED-PUBLIC-PAGE:v1 -->';
const DOC_MARKER = 'Kitchen AI generated by scripts/build.mjs';
const VERIFIED_RIGHTS = new Set(['OWNED', 'LICENSED', 'OFFICIAL_EMBED_ALLOWED', 'PUBLIC_DOMAIN']);
const EMBED_HOSTS = new Set(['www.youtube.com', 'youtube.com', 'www.youtube-nocookie.com', 'youtube-nocookie.com', 'player.vimeo.com']);

const esc = (value) => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const jsonForHtml = (value) => JSON.stringify(value).replaceAll('<', '\\u003c').replaceAll('>', '\\u003e').replaceAll('&', '\\u0026');
const clean = (value) => typeof value === 'string' ? value.trim() : '';
const list = (value) => Array.isArray(value) ? value.map(clean).filter(Boolean) : [];
const isHttpsUrl = (value) => { try { return new URL(value).protocol === 'https:'; } catch { return false; } };
const isHttpsResource = (value) => { try { return new URL(value, 'https://placeholder.invalid').protocol === 'https:'; } catch { return false; } };
const isIsoDuration = (value) => /^PT(?=\d)(?:(?:\d+)H)?(?:(?:\d+)M)?(?:(?:\d+(?:\.\d+)?)S)?$/.test(clean(value));
const baseUrl = (value) => { const url = new URL(value); if (url.protocol !== 'https:') throw new Error('baseUrl must use HTTPS'); return url.href.endsWith('/') ? url.href : `${url.href}/`; };

export function slugFor(video) {
  const source = clean(video.slug) || `${clean(video.title)}-${clean(video.video_id)}`;
  const slug = source.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase()
    .replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 100);
  return slug;
}

export function eligibility(video) {
  const issues = [];
  if (!clean(video.video_id)) issues.push('video_id ausente');
  if (video.status !== 'PUBLISHED') issues.push('status não é PUBLISHED');
  if (!VERIFIED_RIGHTS.has(video.rights_status)) issues.push('direitos não verificados');
  if (!clean(video.provenance?.evidence_url) || !isHttpsUrl(video.provenance.evidence_url)) issues.push('evidência de proveniência ausente ou inválida');
  if (clean(video.title).length < 3) issues.push('título ausente/inválido');
  if (clean(video.description).length < 15) issues.push('descrição insuficiente');
  if (!clean(video.editorial_summary) || clean(video.editorial_summary).length < 60) issues.push('resumo editorial insuficiente');
  if (!clean(video.source) || !isHttpsUrl(video.source_url)) issues.push('origem ou URL-fonte inválida');
  if (!clean(video.thumbnail) || !isHttpsResource(clean(video.thumbnail))) issues.push('thumbnail ausente/inválida');
  if (!clean(video.content_type)) issues.push('content_type ausente');
  if (!clean(video.language)) issues.push('language ausente');
  if (!clean(video.attribution)) issues.push('atribuição ausente');
  if (clean(video.duration) && !isIsoDuration(video.duration)) issues.push('duration não está em ISO 8601');
  if (!slugFor(video)) issues.push('slug inválido');
  if (video.rights_status === 'OFFICIAL_EMBED_ALLOWED' && !isOfficialEmbed(video.embed_url)) issues.push('permissão de incorporação sem URL oficial validável');
  return { eligible: issues.length === 0, issues };
}

export function isOfficialEmbed(value) {
  try {
    const url = new URL(value);
    return url.protocol === 'https:' && EMBED_HOSTS.has(url.hostname) &&
      ((url.hostname.includes('youtube') && url.pathname.startsWith('/embed/')) ||
       (url.hostname === 'player.vimeo.com' && url.pathname.startsWith('/video/')));
  } catch { return false; }
}

export function evaluateCatalog(videos) {
  if (!Array.isArray(videos)) throw new Error('data/videos.json must contain an array');
  const ids = new Set();
  const slugs = new Set();
  const eligible = [];
  const excluded = [];
  for (const video of videos) {
    if (!video || typeof video !== 'object' || Array.isArray(video)) throw new Error('every catalog entry must be an object');
    const id = clean(video.video_id);
    if (id && ids.has(id)) throw new Error(`duplicate video_id: ${id}`);
    if (id) ids.add(id);
    const slug = slugFor(video);
    if (slug && slugs.has(slug)) throw new Error(`duplicate public slug: ${slug}`);
    if (slug) slugs.add(slug);
    const result = eligibility(video);
    (result.eligible ? eligible : excluded).push({ video, slug, issues: result.issues });
  }
  return { eligible, excluded };
}

function videoTitle(video, slug) {
  const base = clean(video.seo_title) || clean(video.title);
  return `${base} — ${clean(video.video_id)} | Kitchen AI`;
}
function videoDescription(video) {
  const base = clean(video.seo_description) || `${clean(video.title)}. ${clean(video.editorial_summary)}`;
  return `${base} · ${clean(video.video_id)}`;
}
function sitePath(site) { return new URL(site.baseUrl).pathname; }
function abs(site, relativePath) { return new URL(relativePath.replace(/^\//, ''), baseUrl(site.baseUrl)).href; }
function safeImage(video, site) { return new URL(clean(video.thumbnail), baseUrl(site.baseUrl)).href; }
function safeEmbed(video) {
  if (!isOfficialEmbed(video.embed_url)) return '';
  if (video.rights_status !== 'OFFICIAL_EMBED_ALLOWED' && !['OWNED', 'LICENSED', 'PUBLIC_DOMAIN'].includes(video.rights_status)) return '';
  return new URL(video.embed_url).href;
}
function dateOnly(value) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(clean(value))) return '';
  try { return new Date(`${value}T00:00:00Z`).toISOString().slice(0, 10) === value ? value : ''; }
  catch { return ''; }
}
function display(label, value) { return clean(value) ? `<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>` : ''; }
function chips(label, values) { const items = list(values); return items.length ? `<section class="detail-card"><h2>${esc(label)}</h2><div class="entity-chips">${items.map((item) => `<span>${esc(item)}</span>`).join('')}</div></section>` : ''; }

export function relatedVideos(video, candidates, limit = 4) {
  const fields = ['entities', 'ingredients', 'techniques'];
  const ownSets = Object.fromEntries(fields.map((field) => [field, new Set(list(video[field]).map((v) => v.toLocaleLowerCase()))]));
  return candidates.filter((entry) => entry.video.video_id !== video.video_id).map((entry) => {
    const other = entry.video;
    let score = 0;
    for (const field of fields) for (const item of list(other[field])) if (ownSets[field].has(item.toLocaleLowerCase())) score += field === 'entities' ? 5 : field === 'ingredients' ? 3 : 2;
    if (clean(video.dish) && clean(video.dish).toLocaleLowerCase() === clean(other.dish).toLocaleLowerCase()) score += 4;
    if (clean(video.chef) && clean(video.chef).toLocaleLowerCase() === clean(other.chef).toLocaleLowerCase()) score += 4;
    if (clean(video.restaurant) && clean(video.restaurant).toLocaleLowerCase() === clean(other.restaurant).toLocaleLowerCase()) score += 4;
    if (clean(video.country) && clean(video.country).toLocaleLowerCase() === clean(other.country).toLocaleLowerCase()) score += 1;
    if (clean(video.season) && clean(video.season).toLocaleLowerCase() === clean(other.season).toLocaleLowerCase()) score += 1;
    return { ...entry, score };
  }).filter((entry) => entry.score > 0).sort((a, b) => b.score - a.score || clean(a.video.title).localeCompare(clean(b.video.title))).slice(0, limit);
}

export function renderVideoPage(video, slug, candidates, site) {
  const canonical = abs(site, `video/${slug}/`);
  const title = videoTitle(video, slug);
  const description = videoDescription(video);
  const root = baseUrl(site.baseUrl);
  const backUrl = `${sitePath(site)}#library`;
  const embed = safeEmbed(video);
  const nativeUrl = ['OWNED', 'LICENSED', 'PUBLIC_DOMAIN'].includes(video.rights_status) && isHttpsUrl(video.native_media_url) ? new URL(video.native_media_url).href : '';
  const image = safeImage(video, site);
  const breadcrumb = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Kitchen AI', item: root },
    { '@type': 'ListItem', position: 2, name: 'Biblioteca', item: `${root}#library` },
    { '@type': 'ListItem', position: 3, name: clean(video.title), item: canonical }
  ] };
  const uploadDate = dateOnly(video.publication_date);
  const videoObject = (embed || nativeUrl) && uploadDate ? {
    '@context': 'https://schema.org', '@type': 'VideoObject', name: clean(video.title), description: clean(video.description),
    thumbnailUrl: image, uploadDate, ...(isIsoDuration(video.duration) ? { duration: clean(video.duration) } : {}),
    ...(embed ? { embedUrl: embed } : { contentUrl: nativeUrl })
  } : null;
  const structured = videoObject ? `${jsonForHtml(breadcrumb)}\n${jsonForHtml(videoObject)}` : jsonForHtml(breadcrumb);
  const player = nativeUrl ? `<div class="native-player"><video controls preload="metadata" poster="${esc(image)}" src="${esc(nativeUrl)}">Seu navegador não oferece reprodução de vídeo.</video></div>` :
    embed ? `<div class="player-frame"><iframe src="${esc(embed)}" title="${esc(video.title)}" loading="lazy" allow="accelerometer; autoplay; encrypted-media; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>` :
    `<section class="editorial-fallback"><h2>Descoberta editorial</h2><p>${esc(video.editorial_summary)}</p><p>Este registro não inclui um player autorizado disponível no momento. A descoberta continua aqui; a reprodução externa não é contornada.</p></section>`;
  const entityItems = list(video.entities);
  const location = [video.city, video.country].map(clean).filter(Boolean).join(', ');
  const related = relatedVideos(video, candidates).map((entry) => `<a class="related-card" href="${esc(`${sitePath(site)}video/${entry.slug}/`)}"><strong>${esc(entry.video.title)}</strong><small>${esc(entry.video.content_type)}${entry.video.country ? ` · ${esc(entry.video.country)}` : ''}</small></a>`).join('');
  const alternateGroup = clean(video.translation_group);
  const hreflang = alternateGroup ? candidates.filter((entry) => entry.video.translation_group === alternateGroup && /^[a-z]{2,3}(-[A-Za-z0-9]{2,8})*$/.test(clean(entry.video.language))).map((entry) => `<link rel="alternate" hreflang="${esc(entry.video.language)}" href="${esc(abs(site, `video/${entry.slug}/`))}">`).join('\n') : '';
  const body = `<main class="detail-page">
    <header class="detail-top"><a class="detail-brand" href="${esc(backUrl)}">KITCHEN AI GLOBAL</a><nav class="breadcrumbs-detail" aria-label="Breadcrumb"><a href="${esc(backUrl)}">Biblioteca</a> / ${esc(video.title)}</nav></header>
    <article>
      <header class="detail-hero"><div class="eyebrow">${esc(video.content_type)}${video.country ? ` · ${esc(video.country)}` : ''}</div><h1>${esc(video.title)}</h1><p class="detail-summary">${esc(video.editorial_summary)}</p></header>
      ${player}
      <div class="detail-columns"><div>
        <section class="detail-card"><h2>Sobre este conteúdo</h2><p>${esc(video.description)}</p>${entityItems.length ? `<div class="entity-chips">${entityItems.map((item) => `<span>${esc(item)}</span>`).join('')}</div>` : ''}</section>
        ${chips('Ingredientes identificados', video.ingredients)}${chips('Técnicas identificadas', video.techniques)}
        ${related ? `<section class="detail-card"><h2>Próximas descobertas</h2><div class="related-grid">${related}</div></section>` : ''}
      </div><aside><section class="detail-card"><h2>Entidades gastronômicas</h2><dl>${display('Prato', video.dish)}${display('Chef', video.chef)}${display('Restaurante', video.restaurant)}${display('Localização', location)}${display('Idioma', video.language)}${display('Duração', video.duration)}${display('Temporada', video.season)}</dl><a class="detail-cta" href="${esc(backUrl)}">Explorar biblioteca →</a></section><p class="attribution">Atribuição: ${esc(video.attribution)}<br>Origem: <a class="source-link" href="${esc(video.source_url)}" rel="noopener noreferrer" target="_blank">${esc(video.source)}</a></p></aside></div>
    </article><footer class="footer"><span>KITCHEN AI GLOBAL · Conteúdo e direitos verificados antes da publicação</span><a href="${esc(backUrl)}">Voltar à biblioteca</a></footer>
  </main>`;
  return `${MARKER}\n<!doctype html><html lang="${esc(video.language)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(canonical)}"><meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:type" content="website"><meta property="og:site_name" content="Kitchen AI Global"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(canonical)}"><meta property="og:image" content="${esc(image)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${esc(image)}">${hreflang}<link rel="stylesheet" href="${esc(`${sitePath(site)}assets/app.css`)}"><script type="application/ld+json">${structured}</script></head><body>${body}</body></html>\n`;
}

export function renderSitemap(entries, site) {
  const urls = [baseUrl(site.baseUrl), ...entries.map((entry) => abs(site, `video/${entry.slug}/`))];
  return `<?xml version="1.0" encoding="UTF-8"?>\n<!-- ${DOC_MARKER} -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map((url) => `  <url><loc>${esc(url)}</loc></url>`).join('\n')}\n</urlset>\n`;
}
export function renderRobots(site) {
  return `# ${DOC_MARKER}\nUser-agent: *\nAllow: /\nDisallow: /content/\nDisallow: /scripts/\nDisallow: /tests/\nSitemap: ${abs(site, 'sitemap.xml')}\n`;
}

async function removeStaleGeneratedPages(root, keepPaths) {
  const base = path.join(root, 'video');
  let entries;
  try { entries = await fs.readdir(base, { withFileTypes: true }); } catch { return; }
  async function walk(dir) {
    for (const item of await fs.readdir(dir, { withFileTypes: true })) {
      const file = path.join(dir, item.name);
      if (item.isDirectory()) await walk(file);
      else if (item.name === 'index.html') {
        const body = await fs.readFile(file, 'utf8');
        const relative = path.relative(root, file).split(path.sep).join('/');
        if (body.includes(MARKER) && !keepPaths.has(relative)) await fs.rm(file);
      }
    }
    if (dir !== base && (await fs.readdir(dir)).length === 0) await fs.rmdir(dir);
  }
  for (const entry of entries) if (entry.isDirectory()) await walk(path.join(base, entry.name));
}

export async function build({ root = ROOT, write = false } = {}) {
  const [source, site] = await Promise.all([
    fs.readFile(path.join(root, 'data/videos.json'), 'utf8').then(JSON.parse),
    fs.readFile(path.join(root, 'content/site.json'), 'utf8').then(JSON.parse)
  ]);
  if (!site?.baseUrl) throw new Error('content/site.json must include an explicit baseUrl');
  baseUrl(site.baseUrl);
  const { eligible, excluded } = evaluateCatalog(source);
  const expected = new Map(eligible.map(({ video, slug }) => [`video/${slug}/index.html`, renderVideoPage(video, slug, eligible, site)]));
  expected.set('sitemap.xml', renderSitemap(eligible, site));
  expected.set('robots.txt', renderRobots(site));
  if (write) {
    await removeStaleGeneratedPages(root, new Set(expected.keys()));
    for (const [relative, content] of expected) {
      const destination = path.join(root, relative);
      await fs.mkdir(path.dirname(destination), { recursive: true });
      try {
        const old = await fs.readFile(destination, 'utf8');
        if (!old.includes(MARKER) && !old.includes(DOC_MARKER)) throw new Error(`refusing to overwrite unmanaged file ${relative}`);
      } catch (error) { if (error.code !== 'ENOENT') throw error; }
      await fs.writeFile(destination, content, 'utf8');
    }
  } else {
    for (const [relative, expectedText] of expected) {
      let actual;
      try { actual = await fs.readFile(path.join(root, relative), 'utf8'); }
      catch { throw new Error(`generated file missing or stale: ${relative}; run npm run build:write`); }
      if (actual !== expectedText) throw new Error(`generated file differs from current source: ${relative}; run npm run build:write`);
    }
    for (const entry of eligible) {
      const relative = `video/${entry.slug}/index.html`;
      if (!expected.has(relative)) throw new Error(`unexpected output ${relative}`);
    }
  }
  return { eligible: eligible.length, excluded: excluded.length, issues: excluded.map(({ video, issues }) => ({ video_id: clean(video.video_id) || '(missing)', issues })) };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = new Set(process.argv.slice(2));
  if (args.has('--write') === args.has('--check')) {
    console.error('Use exactly one of --write or --check');
    process.exit(2);
  }
  try {
    const result = await build({ write: args.has('--write') });
    console.log(`${args.has('--write') ? 'WRITE' : 'CHECK'}: ${result.eligible} página(s) pública(s) elegível(is); ${result.excluded} registro(s) excluído(s)/em revisão.`);
    if (result.issues.length) for (const row of result.issues) console.log(`REQUIRES_VERIFICATION ${row.video_id}: ${row.issues.join('; ')}`);
  } catch (error) {
    console.error(error.message);
    process.exit(1);
  }
}
